name: "[Jinx] Unittest"

defaults:
  run:
    working-directory: tests

on:
  push:
  pull_request:
jobs:
  run:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: tests
    container:
      image: python:3.6.8
    steps:
    - uses: actions/checkout@v2
    - name: Run Test
      run: |
        python -V
        pip install coverage
        pip uninstall pycrypto -y
        pip uninstall pycryptodome -y
        pip install pycryptodome
        ls -alth
        source ./env.sh
        echo ${JINX_DEV_MODE}
